### ISSUE TITLE
Missing radical?

### ISSUE THREAD

**Issue by diyclassics** [PonteIneptique/collatinus-python#18]
When creating an instance of ```Lemmatiseur```, I get the following warning:
```
env/lib/python3.6/site-packages/pycollatinus/parser.py:335: MissingRadical: honor has no radical 1
warnings.warn(gr + " has no radical {}".format(numRad), MissingRadical)
```

Here is the complete list of words: honor, aer, tethys, opes, dos, corpus, ciuis, thales, poesis, manes, turris, uis, nauis, apis, mare, moenia, animal, mille, ille.

The lemmatizer appears to work fine (including for these words), so I can just ignore the warning for now. Anything I should look out for?

**Comment by PonteIneptique** [comment]
Hey @diyclassics :)
I have added a `debug` parameter to issue warning only when people are willing to. These lines are actually issued because the source data of collatinus have inconsistencies (the missing lines do not break the code, hence the warning).
If the fix is good to you, I'll close the issue

**Comment by PonteIneptique** [comment]
Definitely missed that, running it locally, PR incoming

**Comment by PonteIneptique** [comment]
I actually missed the branch. It's on master. If you confirm, I do a release on pypi :)

**Comment by diyclassics** [comment]
I see ```debug``` on master. Thanks!
